services:
  nextcloud:
    image: nextcloud:32-apache
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      # código, config, apps
      - $PWD/var/data/nextcloud:/var/www/html
      # dados dos usuários (NFS via volume Docker)
      - nextcloud-data:/var/www/html/data
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    networks:
      - nextcloud_internal
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      # Router HTTPS
      - "traefik.http.routers.nextcloud.rule=Host(`drive.${DOCKER_DOMAIN}`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=letsencrypt"

      # Serviço
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

      # Headers recomendados pelo Nextcloud
      - "traefik.http.middlewares.nextcloud-headers.headers.customRequestHeaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-headers"
volumes:
  # dados em NFS (TrueNAS)
  nextcloud-data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=truenas-dmz.mfcaetano.lan,vers=4.1,rsize=1048576,wsize=1048576,timeo=600,retrans=5
      device: :/mnt/vault/secure/data
networks:
  traefik:
    external: true
  nextcloud_internal:
    external: true
