services:
  traefik:
    image: traefik:v3.6
    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(dashboard.${DOCKER_DOMAIN})"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - $PWD/traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/certs:/certs

  whoami:
    image: traefik/whoami
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(whoami.${DOCKER_DOMAIN})"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=letsencrypt"

